# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(602, 476)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ipList = QtWidgets.QListWidget(self.tab)
        self.ipList.setObjectName("ipList")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.ipList.addItem(item)
        self.verticalLayout.addWidget(self.ipList)
        self.startButton = QtWidgets.QPushButton(self.tab)
        self.startButton.setObjectName("startButton")
        self.verticalLayout.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(self.tab)
        self.stopButton.setEnabled(False)
        self.stopButton.setObjectName("stopButton")
        self.verticalLayout.addWidget(self.stopButton)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.cmd_line = QtWidgets.QLineEdit(self.tab_2)
        self.cmd_line.setObjectName("cmd_line")
        self.verticalLayout_3.addWidget(self.cmd_line)
        self.send_cmd_btn = QtWidgets.QPushButton(self.tab_2)
        self.send_cmd_btn.setEnabled(True)
        self.send_cmd_btn.setAutoDefault(True)
        self.send_cmd_btn.setDefault(False)
        self.send_cmd_btn.setFlat(False)
        self.send_cmd_btn.setObjectName("send_cmd_btn")
        self.verticalLayout_3.addWidget(self.send_cmd_btn)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.start_report_btn = QtWidgets.QPushButton(self.tab_3)
        self.start_report_btn.setObjectName("start_report_btn")
        self.gridLayout_2.addWidget(self.start_report_btn, 1, 0, 1, 1)
        self.connect_report_btn = QtWidgets.QPushButton(self.tab_3)
        self.connect_report_btn.setObjectName("connect_report_btn")
        self.gridLayout_2.addWidget(self.connect_report_btn, 0, 0, 1, 1)
        self.stop_report_btn = QtWidgets.QPushButton(self.tab_3)
        self.stop_report_btn.setObjectName("stop_report_btn")
        self.gridLayout_2.addWidget(self.stop_report_btn, 2, 0, 1, 1)
        self.reportList = QtWidgets.QListWidget(self.tab_3)
        self.reportList.setObjectName("reportList")
        self.gridLayout_2.addWidget(self.reportList, 4, 0, 1, 1)
        self.plot_btn = QtWidgets.QPushButton(self.tab_3)
        self.plot_btn.setObjectName("plot_btn")
        self.gridLayout_2.addWidget(self.plot_btn, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 602, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.actionReport = QtWidgets.QAction(MainWindow)
        self.actionReport.setObjectName("actionReport")
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "V2X"))
        __sortingEnabled = self.ipList.isSortingEnabled()
        self.ipList.setSortingEnabled(False)
        item = self.ipList.item(0)
        item.setText(_translate("MainWindow", "ID: Host"))
        self.ipList.setSortingEnabled(__sortingEnabled)
        self.startButton.setText(_translate("MainWindow", "Listen"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Clients"))
        self.label.setText(_translate("MainWindow", "Select a client and send command:"))
        self.send_cmd_btn.setText(_translate("MainWindow", "Send"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Send cmd"))
        self.start_report_btn.setText(_translate("MainWindow", "Start"))
        self.connect_report_btn.setText(_translate("MainWindow", "Connect"))
        self.stop_report_btn.setText(_translate("MainWindow", "Stop"))
        self.plot_btn.setText(_translate("MainWindow", "Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Report"))
        self.actionReport.setText(_translate("MainWindow", "Report"))
        self.actionInfo.setText(_translate("MainWindow", "Info"))
